spring:
  config:
    activate:
      on-profile: prod
    import:
      - application-common.yml
      - optional:file:.env.prod[.properties]

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  flyway:
    enabled: true

  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 5
      connection-timeout: 30000

url:
  origin:
    prod: ${URL_ORIGIN_PROD}
    dev: ${URL_ORIGIN_DEV}
    local: ${URL_ORIGIN_LOCAL}

logging:
  discord:
    webhook-url: ${DISCORD_LOG_WEBHOOK_URL}

server:
  tomcat:
    threads:
      max: 15
      min-spare: 5
    accept-count: 5
