name: Chromatic Deployment

on:
  pull_request:
    branches: [fe/dev]

jobs:
  chromatic:
    name: Chromatic Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ./frontend/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('./frontend/yarn.lock') }}

      - run: yarn
        working-directory: ./frontend

      # 내부 리포지토리 PR만 Chromatic 실행
      - name: Run Chromatic
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: chromaui/action@latest
        with:
          workingDir: ./frontend
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
